name: 'Terraform init azurerm backend'
description: 'Runs Terraform init using the azurerm backend configuration, and saves the state file in an Azure storage account'
branding:
  icon: 'aperture'  
  color: 'blue'
inputs:
  azure_credentials: 
    description:  'Azure Credentials in JSON format'
    required: true
  resource_group_name:
    description:  'State file location - resource group name'
    required: true
  container_name:
    description:  'State file location - container name'
    required: true
  storage_account_name:
    description:  'State file location - storage account name'
    required: true
  file_name:
    description:  'State file location - file name'
    required: false
    default: 'terraform.tfstate'
  subscription_id:
    description:  'Subscription Id of the resource group'
    required: false
    default: 'empty'
  tf_working_directory:
    description:  'Terraform working directory'
    required: false
    default: '.'
  
runs:
  using: "composite"
  steps:
    - id: terraformazurerminit
      run: ${{ github.action_path }}/terraform-init.ps1 -subscription_id ${{ inputs.subscription_id }} -resource_group_name ${{ inputs.resource_group_name }} -container_name ${{ inputs.container_name }} -storage_account_name ${{ inputs.storage_account_name }} -file_name ${{ inputs.file_name }} -directory ${{ inputs.tf_working_directory }} -azure_credentials '${{ inputs.Azure_Credentials }}'
      shell: pwsh
